In [18]:
import pandas as pd
import numpy as np

In [19]:
test = pd.read_csv('new_test.csv')

In [20]:
dict = {'강원도':10120, '대전광역시':10640, '부산광역시':21600, '울산광역시':11320, '충청남도':10000}

In [21]:
region = pd.DataFrame(dict,index=dict.keys()).T
region = region['강원도']
region['부산광역시']

21600

In [22]:
test['임대보증금'] = test['임대보증금'].astype(float)
test['임대료'] = test['임대료'].astype(float)
test['전용면적'] = test['전용면적'].astype(float)

In [5]:
# train[train['임대건물구분'] == '상가']

In [23]:
mapping_values = []
for r in test[test['임대건물구분'] == '상가'].values:
    print(r)
    mapping_values.append(r[6] * region[r[4]])

test.loc[test['임대건물구분']=='상가','임대료'] = mapping_values

test[test['임대건물구분'] == '상가'].head()

[80 'C1006' 1505 '상가' '대전광역시' '임대상가' 38.0 1 27.0 'D' nan nan 2.0 5.0 428.0]
[82 'C1006' 1505 '상가' '대전광역시' '임대상가' 37.26 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[83 'C1006' 1505 '상가' '대전광역시' '임대상가' 37.41 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[86 'C1006' 1505 '상가' '대전광역시' '임대상가' 37.49 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[87 'C1006' 1505 '상가' '대전광역시' '임대상가' 37.95 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[89 'C1006' 1505 '상가' '대전광역시' '임대상가' 38.04 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[90 'C1006' 1505 '상가' '대전광역시' '임대상가' 39.33 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[91 'C1006' 1505 '상가' '대전광역시' '임대상가' 39.93 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[93 'C1006' 1505 '상가' '대전광역시' '임대상가' 54.51 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[96 'C1006' 1505 '상가' '대전광역시' '임대상가' 54.6 1 27.0 'D' nan nan 2.0 5.0 428.0]
[97 'C1006' 1505 '상가' '대전광역시' '임대상가' 54.61 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[98 'C1006' 1505 '상가' '대전광역시' '임대상가' 75.98 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[99 'C1006' 1505 '상가' '대전광역시' '임대상가' 583.4 1 27.0 'D' nan nan 2.0 5.0
 428.0]
[116 'C2676' 2572 '상가' '부산광역시' '임대상가' 15.0 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[118 'C2676' 2572 '상가' '부산광역시' '임대상가' 38.0 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[120 'C2676' 2572 '상가' '부산광역시' '임대상가' 16.57 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[121 'C2676' 2572 '상가' '부산광역시' '임대상가' 18.38 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[123 'C2676' 2572 '상가' '부산광역시' '임대상가' 20.9 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[127 'C2676' 2572 '상가' '부산광역시' '임대상가' 21.94 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[128 'C2676' 2572 '상가' '부산광역시' '임대상가' 23.35 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[129 'C2676' 2572 '상가' '부산광역시' '임대상가' 26.25 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[131 'C2676' 2572 '상가' '부산광역시' '임대상가' 28.38 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[132 'C2676' 2572 '상가' '부산광역시' '임대상가' 28.5 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[133 'C2676' 2572 '상가' '부산광역시' '임대상가' 33.15 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[134 'C2676' 2572 '상가' '부산광역시' '임대상가' 33.31 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[135 'C2676' 2572 '상가' '부산광역시' '임대상가' 33.39 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[136 'C2676' 2572 '상가' '부산광역시' '임대상가' 33.51 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[139 'C2676' 2572 '상가' '부산광역시' '임대상가' 37.26 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[140 'C2676' 2572 '상가' '부산광역시' '임대상가' 37.41 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[143 'C2676' 2572 '상가' '부산광역시' '임대상가' 37.49 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[144 'C2676' 2572 '상가' '부산광역시' '임대상가' 37.95 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[146 'C2676' 2572 '상가' '부산광역시' '임대상가' 38.04 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[147 'C2676' 2572 '상가' '부산광역시' '임대상가' 39.33 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[150 'C2676' 2572 '상가' '부산광역시' '임대상가' 40.39 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[151 'C2676' 2572 '상가' '부산광역시' '임대상가' 54.51 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[154 'C2676' 2572 '상가' '부산광역시' '임대상가' 54.6 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[155 'C2676' 2572 '상가' '부산광역시' '임대상가' 54.61 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[156 'C2676' 2572 '상가' '부산광역시' '임대상가' 75.98 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[157 'C2676' 2572 '상가' '부산광역시' '임대상가' 404.65 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[158 'C2676' 2572 '상가' '부산광역시' '임대상가' 583.4 1 25.0 'D' nan nan 0.0 2.0
 418.0]
[171 'C2177' 1245 '상가' '충청남도' '임대상가' 15.0 1 2.0 'D' nan nan nan 1.0 187.0]
[173 'C2177' 1245 '상가' '충청남도' '임대상가' 16.57 1 2.0 'D' nan nan nan 1.0 187.0]
[174 'C2177' 1245 '상가' '충청남도' '임대상가' 18.38 1 2.0 'D' nan nan nan 1.0 187.0]
[176 'C2177' 1245 '상가' '충청남도' '임대상가' 20.9 1 2.0 'D' nan nan nan 1.0 187.0]
[180 'C2177' 1245 '상가' '충청남도' '임대상가' 21.94 1 2.0 'D' nan nan nan 1.0 187.0]
[181 'C2177' 1245 '상가' '충청남도' '임대상가' 23.35 1 2.0 'D' nan nan nan 1.0 187.0]
[182 'C2177' 1245 '상가' '충청남도' '임대상가' 26.25 1 2.0 'D' nan nan nan 1.0 187.0]
[184 'C2177' 1245 '상가' '충청남도' '임대상가' 28.5 1 2.0 'D' nan nan nan 1.0 187.0]
[185 'C2177' 1245 '상가' '충청남도' '임대상가' 33.15 1 2.0 'D' nan nan nan 1.0 187.0]
[186 'C2177' 1245 '상가' '충청남도' '임대상가' 33.31 1 2.0 'D' nan nan nan 1.0 187.0]
[187 'C2177' 1245 '상가' '충청남도' '임대상가' 33.39 1 2.0 'D' nan nan nan 1.0 187.0]
[188 'C2177' 1245 '상가' '충청남도' '임대상가' 33.51 1 2.0 'D' nan nan nan 1.0 187.0]
[190 'C2177' 1245 '상가' '충청남도' '임대상가' 40.39 1 2.0 'D' nan nan nan 1.0 187.0]
[191 'C2177' 1245 '상가' '충청남도' '임대상가' 61.89 1 2.0 'D' nan nan nan 1.0 187.0]
[192 'C2177' 1245 '상가' '충청남도' '임대상가' 401.5 1 2.0 'D' nan nan nan 1.0 187.0]
[201 'C2033' 1400 '상가' '울산광역시' '임대상가' 15.0 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[203 'C2033' 1400 '상가' '울산광역시' '임대상가' 16.57 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[204 'C2033' 1400 '상가' '울산광역시' '임대상가' 18.38 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[206 'C2033' 1400 '상가' '울산광역시' '임대상가' 20.9 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[210 'C2033' 1400 '상가' '울산광역시' '임대상가' 21.94 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[211 'C2033' 1400 '상가' '울산광역시' '임대상가' 23.35 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[212 'C2033' 1400 '상가' '울산광역시' '임대상가' 26.25 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[214 'C2033' 1400 '상가' '울산광역시' '임대상가' 28.5 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[215 'C2033' 1400 '상가' '울산광역시' '임대상가' 33.15 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[216 'C2033' 1400 '상가' '울산광역시' '임대상가' 33.31 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[217 'C2033' 1400 '상가' '울산광역시' '임대상가' 33.39 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[218 'C2033' 1400 '상가' '울산광역시' '임대상가' 33.51 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[220 'C2033' 1400 '상가' '울산광역시' '임대상가' 40.39 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[221 'C2033' 1400 '상가' '울산광역시' '임대상가' 61.89 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[222 'C2033' 1400 '상가' '울산광역시' '임대상가' 401.5 1 12.0 'D' nan nan 0.0 7.0
 308.0]
[233 'C1812' 1021 '상가' '울산광역시' '임대상가' 9.96 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[234 'C1812' 1021 '상가' '울산광역시' '임대상가' 13.07 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[235 'C1812' 1021 '상가' '울산광역시' '임대상가' 13.59 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[236 'C1812' 1021 '상가' '울산광역시' '임대상가' 14.25 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[240 'C1812' 1021 '상가' '울산광역시' '임대상가' 19.15 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[241 'C1812' 1021 '상가' '울산광역시' '임대상가' 22.89 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[242 'C1812' 1021 '상가' '울산광역시' '임대상가' 23.25 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[243 'C1812' 1021 '상가' '울산광역시' '임대상가' 27.75 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[252 'C1812' 1021 '상가' '울산광역시' '임대상가' 28.19 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[253 'C1812' 1021 '상가' '울산광역시' '임대상가' 42.35 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[254 'C1812' 1021 '상가' '울산광역시' '임대상가' 55.17 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[256 'C1812' 1021 '상가' '울산광역시' '임대상가' 248.56 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[257 'C1812' 1021 '상가' '울산광역시' '임대상가' 253.71 1 22.0 'D' nan nan 0.0 4.0
 185.0]
[261 'C2253' 1161 '상가' '강원도' '임대상가' 13.77 1 0.0 'D' nan nan 0.0 2.0 173.0]
[262 'C2253' 1161 '상가' '강원도' '임대상가' 22.89 1 0.0 'D' nan nan 0.0 2.0 173.0]
[263 'C2253' 1161 '상가' '강원도' '임대상가' 22.91 1 0.0 'D' nan nan 0.0 2.0 173.0]
[264 'C2253' 1161 '상가' '강원도' '임대상가' 23.79 1 0.0 'D' nan nan 0.0 2.0 173.0]
[266 'C2253' 1161 '상가' '강원도' '임대상가' 23.86 1 0.0 'D' nan nan 0.0 2.0 173.0]
[268 'C2253' 1161 '상가' '강원도' '임대상가' 24.19 1 0.0 'D' nan nan 0.0 2.0 173.0]
[269 'C2253' 1161 '상가' '강원도' '임대상가' 27.75 1 0.0 'D' nan nan 0.0 2.0 173.0]
[275 'C2253' 1161 '상가' '강원도' '임대상가' 28.19 1 0.0 'D' nan nan 0.0 2.0 173.0]
[276 'C2253' 1161 '상가' '강원도' '임대상가' 28.69 1 0.0 'D' nan nan 0.0 2.0 173.0]
[281 'C2253' 1161 '상가' '강원도' '임대상가' 28.93 1 0.0 'D' nan nan 0.0 2.0 173.0]
[283 'C2253' 1161 '상가' '강원도' '임대상가' 42.35 1 0.0 'D' nan nan 0.0 2.0 173.0]
[284 'C2253' 1161 '상가' '강원도' '임대상가' 42.4 1 0.0 'D' nan nan 0.0 2.0 173.0]
[285 'C2253' 1161 '상가' '강원도' '임대상가' 55.17 1 0.0 'D' nan nan 0.0 2.0 173.0]
[286 'C2253' 1161 '상가' '강원도' '임대상가' 55.5 1 0.0 'D' nan nan 0.0 2.0 173.0]
[287 'C2253' 1161 '상가' '강원도' '임대상가' 82.92 1 0.0 'D' nan nan 0.0 2.0 173.0]
[288 'C2253' 1161 '상가' '강원도' '임대상가' 248.56 1 0.0 'D' nan nan 0.0 2.0 173.0]
[316 'C1729' 627 '상가' '강원도' '임대상가' 13.02 1 0.0 'D' nan nan 0.0 5.0 131.0]
[317 'C1729' 627 '상가' '강원도' '임대상가' 18.54 1 0.0 'D' nan nan 0.0 5.0 131.0]
[318 'C1729' 627 '상가' '강원도' '임대상가' 19.08 1 0.0 'D' nan nan 0.0 5.0 131.0]
[319 'C1729' 627 '상가' '강원도' '임대상가' 21.86 1 0.0 'D' nan nan 0.0 5.0 131.0]
[321 'C1729' 627 '상가' '강원도' '임대상가' 22.28 1 0.0 'D' nan nan 0.0 5.0 131.0]
[322 'C1729' 627 '상가' '강원도' '임대상가' 23.4 1 0.0 'D' nan nan 0.0 5.0 131.0]
[326 'C1729' 627 '상가' '강원도' '임대상가' 27.57 1 0.0 'D' nan nan 0.0 5.0 131.0]
[327 'C1729' 627 '상가' '강원도' '임대상가' 32.21 1 0.0 'D' nan nan 0.0 5.0 131.0]
[328 'C1729' 627 '상가' '강원도' '임대상가' 32.46 1 0.0 'D' nan nan 0.0 5.0 131.0]
[329 'C1729' 627 '상가' '강원도' '임대상가' 34.86 1 0.0 'D' nan nan 0.0 5.0 131.0]
[330 'C1729' 627 '상가' '강원도' '임대상가' 35.76 1 0.0 'D' nan nan 0.0 5.0 131.0]
[331 'C1729' 627 '상가' '강원도' '임대상가' 50.08 1 0.0 'D' nan nan 0.0 5.0 131.0]
[332 'C1729' 627 '상가' '강원도' '임대상가' 240.22 1 0.0 'D' nan nan 0.0 5.0 131.0]

,Unnamed: 0,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수
76,80,C1006,1505,상가,대전광역시,임대상가,38.00,1,27.0,D,NaN,404320.0,2.0,5.0,428.0
77,82,C1006,1505,상가,대전광역시,임대상가,37.26,1,27.0,D,NaN,396446.4,2.0,5.0,428.0
78,83,C1006,1505,상가,대전광역시,임대상가,37.41,1,27.0,D,NaN,398042.4,2.0,5.0,428.0
79,86,C1006,1505,상가,대전광역시,임대상가,37.49,1,27.0,D,NaN,398893.6,2.0,5.0,428.0
80,87,C1006,1505,상가,대전광역시,임대상가,37.95,1,27.0,D,NaN,403788.0,2.0,5.0,428.0

In [24]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941 entries, 0 to 940
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    941 non-null    int64
 1   단지코드                          941 non-null    object
 2   총세대수                          941 non-null    int64
 3   임대건물구분                        941 non-null    object
 4   지역                            941 non-null    object
 5   공급유형                          941 non-null    object
 6   전용면적                          941 non-null    float64
 7   전용면적별세대수                      941 non-null    int64
 8   공가수                           941 non-null    float64
 9   자격유형                          941 non-null    object
 10  임대보증금                         829 non-null    float64
 11  임대료                           941 non-null    float64
 12  도보 10분거리 내 지하철역 수(환승노선 수 반영)  907 non-null    float64
 13  도보 10분거리 내 버스정류장 수            941 non-null    float64
 14  단지내주차면수                       941 non-null    float64
dtypes: float64(7), int64(3), object(5)
memory usage: 110.4+ KB

In [27]:
cols = ['임대보증금','도보 10분거리 내 지하철역 수(환승노선 수 반영)','도보 10분거리 내 버스정류장 수']
test[cols] = test[cols].fillna(0)

In [28]:
test.isnull().sum() # 결측치 다채웠다!

Unnamed: 0                      0
단지코드                            0
총세대수                            0
임대건물구분                          0
지역                              0
공급유형                            0
전용면적                            0
전용면적별세대수                        0
공가수                             0
자격유형                            0
임대보증금                           0
임대료                             0
도보 10분거리 내 지하철역 수(환승노선 수 반영)    0
도보 10분거리 내 버스정류장 수              0
단지내주차면수                         0
dtype: int64

In [29]:
test.to_csv('test_final.csv')
# 오류 단지코드 제거
# 임대보증금/임대료 채우기
# 버스정류장/지하철역은 결측치 전부 0으로 채움
# 중복데이터 제거